FROM python:3.10
COPY requirements.txt .
RUN pip install -r requirements.txt
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN pip install flask torch

CMD ["python", "app.py"]
